project:
  type: website

website:
  title: "GenAI in Academia"
  sidebar:
    style: docked
    pinned: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - section: "Fundamentals of GenAI"
        contents:
          - href: fundamentals/01_ecosystem.qmd
            text: The Ecosystem        
          - href: fundamentals/02_models.qmd
            text: Models
          - href: fundamentals/03_agents.qmd
            text: Agents
          - href: fundamentals/04_products.qmd
            text: Products
      - href: resources.qmd
        text: Resources
  page-footer:
    center: "GenAI in Academia | 2026"

format:
  html:
    theme: cosmo
    fontsize: 1.2em
    grid:
      sidebar-width: 300px
    toc: true
    toc-depth: 3
    number-sections: false
    link-external-newwindow: true
    mermaid:
      theme: neutral