project:
  type: website

website:
  title: "GenAI in Academia"
  sidebar:
    style: docked
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - section: "Fundamentals of GenAI"
        contents:
          - href: fundamentals/ecosystem.qmd
            text: The GenAI Ecosystem        
          - href: fundamentals/how-llms-work.qmd
            text: How GenAI Models Work
          - href: fundamentals/key-capabilities.qmd
            text: Key GenAI Capabilities
          - href: fundamentals/choosing-tools.qmd
            text: Choosing the Right Tool
      - href: resources.qmd
        text: Resources
  page-footer:
    center: "GenAI For Teaching and Research | 2026"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    grid:
      sidebar-width: 350px
    css: styles.css
    toc: true
    number-sections: true
    link-external-newwindow: true
    mermaid:
      theme: neutral